//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dairy_Farm_Management_Project_3rd_try.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BreedingRecord
    {

        [Display(Name = "ID")]
        public int BreedingNo { get; set; }

        [Display(Name = "Tag No.")]
        public int TagNo { get; set; }

        [DataType(DataType.DateTime), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Previous Calving Date")]
        public Nullable<System.DateTime> PreviousCalvingDate { get; set; }

        [Display(Name = "Success?")]
        public string SuccessfulSemen { get; set; }


        [DataType(DataType.DateTime), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Test Date")]
        public Nullable<System.DateTime> PregnancyTestDate { get; set; }

        [Display(Name = "Status")]
        public string PregnancyStatus { get; set; }

        [DataType(DataType.DateTime), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Expected Date")]
        public Nullable<System.DateTime> ExpectedCalvingDate { get; set; }

        [DataType(DataType.DateTime), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Actual Date")]
        public Nullable<System.DateTime> ActualCalvingDate { get; set; }
        
        public virtual HerdReport HerdReport { get; set; }
    }
}
