//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dairy_Farm_Management_Project_3rd_try.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HerdReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HerdReport()
        {
            this.BreedingRecords = new HashSet<BreedingRecord>();
            this.DailyMilkProductions = new HashSet<DailyMilkProduction>();
            this.TreatmentReports = new HashSet<TreatmentReport>();
            this.Vaccinations = new HashSet<Vaccination>();
        }
        

        public int TagNo { get; set; }

        [Display(Name = "DOB")]
        [DataType(DataType.DateTime), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> DateOfBirth { get; set; }

        [Display(Name = "Status")]
        public string LifeStatus { get; set; }

        [Display(Name = "Type")]
        public string TypesOfBreed { get; set; }

        [Display(Name = "Gender")]
        public string Gender { get; set; }
        public Nullable<int> Age { get; set; }

        [Display(Name = "Pregnent?")]
        public string ReproductionStatus { get; set; }

        [Display(Name = "Mother")]
        public Nullable<int> TagNoOfMother { get; set; }

        [Display(Name = "Father")]
        public Nullable<int> TagNoOfFather { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BreedingRecord> BreedingRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyMilkProduction> DailyMilkProductions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TreatmentReport> TreatmentReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vaccination> Vaccinations { get; set; }
    }
}
