//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dairy_Farm_Management_Project_3rd_try.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TreatmentReport
    {
        [Display(Name = "Treatment NO.")]
        public int TreatmentNo { get; set; }

        [Display(Name = "Tag No.")]
        public int TagNo { get; set; }

        [DataType(DataType.DateTime), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime Date { get; set; }

        [Display(Name = "Body Temperature")]
        public Nullable<int> BodyTemperature { get; set; }


        public string Symptoms { get; set; }
        public string Treatment { get; set; }
        public string Diagnosis { get; set; }
        public string Medicine { get; set; }
    
        public virtual HerdReport HerdReport { get; set; }
    }
}
