//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dairy_Farm_Management_Project_3rd_try.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Vaccination
    {

        [Display(Name = "Event No.")]
        public int EventNo { get; set; }

        [Display(Name = "Tag No.")]
        public int TagNo { get; set; }

        [Display(Name = "Vaccine No.")]
        public int VaccineNo { get; set; }
    
        public virtual HerdReport HerdReport { get; set; }
        public virtual VaccineDetail VaccineDetail { get; set; }
    }
}
